### ISSUE TITLE
rake db:fixtures:load fails in v0.7.0 from git

### ISSUE THREAD

**Issue by danielblues** [activewarehouse/rails_sql_views#3]
Hi,

 I've installed from git as a plugin with piston, it worked fine until running rake db:fixtures:load returned:

undefined method `tables_with_views_included' for class`ActiveRecord::ConnectionAdapters::SQLite3Adapter'

 I went back to creating the views with SQL, but will try any fixes you may propose. 

Thanks

daniel

<pre>
Ruby version    1.8.7 (x86_64-linux)
RubyGems version    1.3.4
Rack version    1.0
Rails version   2.3.2
Active Record version   2.3.2
Action Pack version 2.3.2
Active Resource version 2.3.2
Action Mailer version   2.3.2
Active Support version  2.3.2
Environment development
Database adapter    sqlite3

rake db:fixtures:load --trace
(in /home/dfb/Documents/ITQB/Projectos/openlabman)
** Invoke db:fixtures:load (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:fixtures:load
rake aborted!
undefined method `tables_with_views_included' for class `ActiveRecord::ConnectionAdapters::SQLite3Adapter'
/home/dfb/Documents/ITQB/Projectos/openlabman/vendor/plugins/rails_sql_views/lib/rails_sql_views/connection_adapters/abstract_adapter.rb:17:in `alias_method'
/home/dfb/Documents/ITQB/Projectos/openlabman/vendor/plugins/rails_sql_views/lib/rails_sql_views/connection_adapters/abstract_adapter.rb:17:in `send'
/home/dfb/Documents/ITQB/Projectos/openlabman/vendor/plugins/rails_sql_views/lib/rails_sql_views/connection_adapters/abstract_adapter.rb:17:in `disable_referential_integrity'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/fixtures.rb:499:in `create_fixtures'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/base.rb:1453:in `silence'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/fixtures.rb:498:in `create_fixtures'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/tasks/databases.rake:218
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/tasks/databases.rake:217:in `each'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/tasks/databases.rake:217
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
</pre>

**Comment by robertwahler** [comment]
I think this is addressed in this commit:
http://github.com/robertwahler/rails_sql_views/commit/73dc70edd6cd1325752642443c1fd3561e52860d

**Comment by danielblues** [comment]
Hi,
 It fixed the problem, thanks.
daniel
